displayName=Slayer Rumours
author=KoveSec
support=https://github.com/KoveSec/slayer-rumours
description=Preferred locations, Shortest Path, and Inventory Setups for your current Slayer task
tags=slayer,task,path,inventory,location
version=
plugins=com.slayerrumeurs.SlayerRumoursPlugin
build=standard
